import { assignCreatorForCatalogSlot, formatCreatorInspiration } from '@/lib/demo-creators'
import { resolveUniqueCatalogMedia } from '@/lib/trend-media-assignment'
import { assertUniqueTrendCatalog } from '@/lib/demo-trend-uniqueness'
import type { TrendIntelligence, TrendVelocity } from '@/types/trend-intelligence'

export const DEMO_CATALOG_NICHES = [
  'Productivity',
  'Fitness',
  'Beauty',
  'Side Hustle',
  'Food',
  'Luxury',
  'Motivation',
  'AI',
  'Business',
  'Fashion',
] as const

export type DemoCatalogNiche = (typeof DEMO_CATALOG_NICHES)[number]

type TrendBlueprint = {
  title: string
  platform: 'TikTok' | 'Instagram'
  hook: string
  hookType: string
  hashtags: string[]
  description: string
  views: string
  engagement: string
  viralScore: number
  velocity: TrendVelocity
  ideas: [string, string]
  altHooks: [string, string]
  pacing: string
  audioTrend: string
  visualStyle: string
}

const GRADIENTS = [
  { from: 'from-violet-600', to: 'to-fuchsia-600' },
  { from: 'from-indigo-500', to: 'to-purple-600' },
  { from: 'from-cyan-500', to: 'to-blue-600' },
  { from: 'from-rose-500', to: 'to-orange-600' },
  { from: 'from-emerald-500', to: 'to-teal-600' },
  { from: 'from-amber-500', to: 'to-yellow-600' },
] as const

const NICHE_BLUEPRINTS: Record<DemoCatalogNiche, TrendBlueprint[]> = {
  Productivity: [
    {
      title: 'POV: 5AM Morning Stack in 47 Sekunden',
      platform: 'TikTok',
      hook: '„POV: Du wachst ohne Snooze — so sieht Stunde 1 aus."',
      hookType: 'POV + Transformation',
      hashtags: ['#morningroutine', '#productivity', '#5amclub', '#deepwork'],
      description: 'Kurze POV-Clips mit Before/After. Starke Watch-Time durch Jump-Cuts und Text-Overlays.',
      views: '2.4M',
      engagement: '9.8%',
      viralScore: 91,
      velocity: 'rising',
      ideas: ['60-Sekunden Morning Stack mit 3 Quick-Wins', 'Duet auf Top-Profil in Productivity'],
      altHooks: ['„Ich hab 21 Tage diese Routine getestet."', '„Das ändert deinen Morgen komplett."'],
      pacing: 'Jump-Cuts alle 1.5s, Text synchron zum Beat',
      audioTrend: 'Lo-fi Morning Motivation Remix',
      visualStyle: 'Warm light, Front-Cam, authentisch',
    },
    {
      title: 'Notion Dashboard Setup — 3 Minuten Template',
      platform: 'Instagram',
      hook: '„So organisierst du dein Leben in einem Screen."',
      hookType: 'Tutorial + Save Trigger',
      hashtags: ['#notion', '#productivity', '#templates', '#organisation'],
      description: 'Screen-Recording mit schnellen Zooms. Hohe Save-Rate durch Template-Versprechen.',
      views: '890K',
      engagement: '7.4%',
      viralScore: 84,
      velocity: 'stable',
      ideas: ['Carousel: 5 Dashboard-Layouts', 'Reel: Setup in Echtzeit'],
      altHooks: ['„Das Template spart mir 2h pro Woche."', '„Organisation ohne Overwhelm."'],
      pacing: 'Screen cap + Voice-over, 2s pro Step',
      audioTrend: 'Soft focus beats — trending auf Reels',
      visualStyle: 'Clean UI, dark mode, minimal text',
    },
    {
      title: 'Deep Work Timer Hack (Pomodoro 2.0)',
      platform: 'TikTok',
      hook: '„Diese Timer-Methode hat meine Fokuszeit verdoppelt."',
      hookType: 'Claim + Proof',
      hashtags: ['#deepwork', '#studytok', '#focus', '#pomodoro'],
      description: 'Talking Head + Timer Overlay. Comments fragen nach App/Setup.',
      views: '1.6M',
      engagement: '8.6%',
      viralScore: 88,
      velocity: 'rising',
      ideas: ['Split: Timer-App vs. Ergebnis-Graph', 'Story: 7-Tage Fokus-Challenge'],
      altHooks: ['„So viel schaffst du in 90 Minuten."', '„Kein Handy mehr beim Arbeiten."'],
      pacing: 'Hook 0–3s, Demo 3–25s, CTA 25–40s',
      audioTrend: 'Ambient focus — Original Voice',
      visualStyle: 'Desk setup, zweiter Monitor, cozy',
    },
    {
      title: 'Sunday Reset Routine — Aesthetic Edition',
      platform: 'Instagram',
      hook: '„Sunday Reset, aber ohne Perfektionismus."',
      hookType: 'Relatable + Aesthetic',
      hashtags: ['#sundayreset', '#thatgirl', '#productivity', '#aesthetic'],
      description: 'Montage: Putzen, Planen, Meal Prep. Save-Worthy für Wochenstart.',
      views: '1.1M',
      engagement: '7.1%',
      viralScore: 82,
      velocity: 'peak',
      ideas: ['Checkliste als Carousel Slide 1', 'ASMR Cleaning Clips'],
      altHooks: ['„So startest du Montag ohne Stress."', '„Reset in unter 60 Minuten."'],
      pacing: 'Slow transitions, 3s pro Task',
      audioTrend: 'Aesthetic piano loop',
      visualStyle: 'Neutral tones, natural light',
    },
    {
      title: 'Inbox Zero in 15 Minuten — Realistisch',
      platform: 'TikTok',
      hook: '„847 ungelesene Mails? Ich zeig dir den Fix."',
      hookType: 'Problem + Number',
      hashtags: ['#emailhack', '#productivity', '#workfromhome', '#desksetup'],
      description: 'Screen + Face Cam. Konkrete Zahl im Hook erhöht CTR.',
      views: '720K',
      engagement: '8.1%',
      viralScore: 79,
      velocity: 'stable',
      ideas: ['3-Filter-System erklären', 'Before/After Inbox Screenshot'],
      altHooks: ['„E-Mail Stress in 15 Minuten weg."', '„Das mache ich jeden Freitag."'],
      pacing: 'Listicle 3 Steps, bold subtitles',
      audioTrend: 'Upbeat corporate lo-fi',
      visualStyle: 'Laptop close-up, clean desk',
    },
    {
      title: 'Habit Tracker — 30 Tage ohne App',
      platform: 'TikTok',
      hook: '„Paper Habit Tracker schlägt jede App — hier ist warum."',
      hookType: 'Contrarian Take',
      hashtags: ['#habittracker', '#atomic habits', '#journaling', '#productivity'],
      description: 'Journal Flip-Through + Ergebnisse. Niedrige Produktionskosten, hohe Shares.',
      views: '540K',
      engagement: '9.2%',
      viralScore: 86,
      velocity: 'rising',
      ideas: ['PDF Template teilen', '30-Tage Progress Montage'],
      altHooks: ['„So bleibst du bei Gewohnheiten dran."', '„Kein Handy-Tracking nötig."'],
      pacing: 'Page turns, macro shots',
      audioTrend: 'Soft vinyl crackle trend',
      visualStyle: 'Flat lay, pen, coffee',
    },
  ],
  Fitness: [
    {
      title: 'Home Workout — 12 Min, kein Equipment',
      platform: 'TikTok',
      hook: '„12 Minuten, die dein Core zerstören (im guten Sinne)."',
      hookType: 'Time Promise + Intensity',
      hashtags: ['#homeworkout', '#fitness', '#coreworkout', '#noequipment'],
      description: 'Follow-along Format mit Timer. Hohe Completion Rate.',
      views: '3.1M',
      engagement: '10.2%',
      viralScore: 93,
      velocity: 'rising',
      ideas: ['3 Varianten für Anfänger/Fortgeschrittene', 'Duet mit Form-Corrections'],
      altHooks: ['„Kein Gym? Kein Problem."', '„So trainierst du in der Küche."'],
      pacing: 'Exercise cuts on beat, rep counter overlay',
      audioTrend: 'Phonk workout remix',
      visualStyle: 'Bright apartment, mat, mirror optional',
    },
    {
      title: 'Gym Progress — 90 Tage Transformation',
      platform: 'Instagram',
      hook: '„Tag 1 vs. Tag 90 — gleiche Pose, andere Energie."',
      hookType: 'Before/After',
      hashtags: ['#gymtok', '#transformation', '#fitnessreels', '#progress'],
      description: 'Side-by-side Reel. Comments: „Welches Programm?"',
      views: '1.8M',
      engagement: '8.4%',
      viralScore: 90,
      velocity: 'peak',
      ideas: ['Carousel: Training Split Übersicht', 'Reel: Top 3 Übungen'],
      altHooks: ['„So sah ich vor 3 Monaten aus."', '„Konsistenz > Motivation."'],
      pacing: 'Match-cut transitions',
      audioTrend: 'Motivational cinematic drop',
      visualStyle: 'Gym lighting, consistent angles',
    },
    {
      title: 'Meal Prep für Muskelaufbau — 40€/Woche',
      platform: 'TikTok',
      hook: '„Bulking ohne Bankrott — 5 Meals, ein Screen."',
      hookType: 'Budget + Listicle',
      hashtags: ['#mealprep', '#bulking', '#fitnessfood', '#macros'],
      description: 'Top-down cooking + Makro-Overlay. Save-Rate hoch bei Fitness-Nische.',
      views: '1.2M',
      engagement: '7.8%',
      viralScore: 85,
      velocity: 'stable',
      ideas: ['Einkaufsliste als Kommentar-Pin', 'Protein-Verteilung Chart'],
      altHooks: ['„So esse ich 3200 kcal günstig."', '„Meal Prep Sonntag in 45 Min."'],
      pacing: 'Fast cuts, ingredient close-ups',
      audioTrend: 'Cooking ASMR + bass',
      visualStyle: 'Kitchen counter, containers',
    },
    {
      title: 'Lauf-Intervalle für Anfänger',
      platform: 'TikTok',
      hook: '„Vom Couch Potato zum 5K — Woche 1 sieht so aus."',
      hookType: 'Journey Start',
      hashtags: ['#running', '#couchto5k', '#cardio', '#runnersofinstagram'],
      description: 'Outdoor POV + Watch Stats. Relatable Einstieg.',
      views: '940K',
      engagement: '8.9%',
      viralScore: 87,
      velocity: 'rising',
      ideas: ['Wochenplan Slide Show', 'Schuh-Review Micro-Segment'],
      altHooks: ['„So fängst du mit Laufen an."', '„Keine Seitenstechen mehr."'],
      pacing: 'Run B-roll, stat overlays',
      audioTrend: 'Running playlist trend',
      visualStyle: 'Golden hour, park path',
    },
    {
      title: 'Mobility Routine — Desk Worker Edition',
      platform: 'Instagram',
      hook: '„8 Minuten und dein lower back dankt dir."',
      hookType: 'Pain Point Relief',
      hashtags: ['#mobility', '#stretching', '#deskjob', '#recovery'],
      description: 'Follow-along stretches. Starke Shares bei Office-Zielgruppe.',
      views: '670K',
      engagement: '7.2%',
      viralScore: 81,
      velocity: 'stable',
      ideas: ['PDF Stretch Guide', 'Morning vs. Evening Routine'],
      altHooks: ['„Nach 8h Büro brauchst du das."', '„Physio-approved Flow."'],
      pacing: 'Slow demo, breath cues on screen',
      audioTrend: 'Calm yoga flow audio',
      visualStyle: 'Minimal studio, yoga mat',
    },
    {
      title: 'Push-Up Challenge — 30 Tage',
      platform: 'TikTok',
      hook: '„Tag 30: 100 Push-Ups — aber Tag 1 war peinlich."',
      hookType: 'Challenge Arc',
      hashtags: ['#pushupchallenge', '#calisthenics', '#fitnesschallenge', '#gains'],
      description: 'Daily counter overlay. Community versucht mitzumachen.',
      views: '2.2M',
      engagement: '9.5%',
      viralScore: 92,
      velocity: 'rising',
      ideas: ['Stitch mit User Attempts', 'Form-Tipps Carousel'],
      altHooks: ['„So baust du Push-Up Kraft auf."', '„Kein Gym Membership nötig."'],
      pacing: 'Rep clips montage',
      audioTrend: 'Rock training beat',
      visualStyle: 'Garage gym aesthetic',
    },
  ],
  Beauty: [
    {
      title: 'Glass Skin Routine — 4 Schritte',
      platform: 'TikTok',
      hook: '„Glass Skin in 4 Schritten — ohne 10 Produkte."',
      hookType: 'Simplification',
      hashtags: ['#glassskin', '#skintok', '#kbeauty', '#skincareroutine'],
      description: 'Close-up application. Produkt-Labels als Text.',
      views: '3.8M',
      engagement: '11.4%',
      viralScore: 94,
      velocity: 'rising',
      ideas: ['AM vs. PM Version', 'Dupes unter 15€'],
      altHooks: ['„So bekommst du den Glow."', '„Dermatologen-freundlich minimal."'],
      pacing: 'Macro skin shots, soft transitions',
      audioTrend: 'Soft K-pop instrumental',
      visualStyle: 'Ring light, bathroom mirror',
    },
    {
      title: 'GRWM Date Night — Drugstore Only',
      platform: 'Instagram',
      hook: '„Full Face nur aus der Drogerie — komplettes GRWM."',
      hookType: 'GRWM + Constraint',
      hashtags: ['#grwm', '#makeupreels', '#drugstoremakeup', '#datenight'],
      description: 'Classic GRWM pacing. Hohe Watch-Time bei Beauty-Audience.',
      views: '1.4M',
      engagement: '7.6%',
      viralScore: 86,
      velocity: 'peak',
      ideas: ['Product list in Caption', 'Before/After Zoom'],
      altHooks: ['„Date Night in 20 Minuten ready."', '„Kein High-End nötig."'],
      pacing: 'Real-time speed ramps',
      audioTrend: 'Trending pop lip-sync',
      visualStyle: 'Vanity setup, warm bulbs',
    },
    {
      title: 'Retinol ohne Purging — Dermatologen-Tipps',
      platform: 'TikTok',
      hook: '„Retinol falsch = rotes Gesicht. So geht’s richtig."',
      hookType: 'Fear + Authority',
      hashtags: ['#retinol', '#skincarescience', '#antiaging', '#dermtok'],
      description: 'Talking head + infographic overlays. Trust-building Content.',
      views: '1.9M',
      engagement: '9.1%',
      viralScore: 91,
      velocity: 'stable',
      ideas: ['Wochenplan Grafik', 'Product pairing Do/Don’t'],
      altHooks: ['„Retinol für Anfänger erklärt."', '„So vermeidest du Irritation."'],
      pacing: 'Educational beats, text cards',
      audioTrend: 'Voice-over only',
      visualStyle: 'Clinical clean, white coat optional',
    },
    {
      title: 'Hair Volume Blowout — 5 Minuten',
      platform: 'TikTok',
      hook: '„Flat hair? Dieser Blowout-Trick ist illegal."',
      hookType: 'Hyperbole + Tutorial',
      hashtags: ['#hairtok', '#blowout', '#hairhacks', '#volume'],
      description: 'Fast tutorial, satisfying before/after. Shares in Hair-Nische.',
      views: '2.6M',
      engagement: '10.8%',
      viralScore: 93,
      velocity: 'rising',
      ideas: ['Curly vs. Straight Variante', 'Tool unter 30€'],
      altHooks: ['„Salon Blowout zu Hause."', '„Mehr Volumen ohne Extensions."'],
      pacing: 'Speed ramp tutorial',
      audioTrend: 'Bouncy hair flip sound',
      visualStyle: 'Salon mirror, golden light',
    },
    {
      title: 'SPF Reapply Hack fürs Büro',
      platform: 'Instagram',
      hook: '„Du trägst SPF morgens auf — und dann passiert das."',
      hookType: 'Myth Bust',
      hashtags: ['#spf', '#sunscreen', '#skincare', '#beautyreels'],
      description: 'Quick educational reel. Save für Sommer-Season.',
      views: '580K',
      engagement: '6.9%',
      viralScore: 78,
      velocity: 'stable',
      ideas: ['SPF over makeup trick', 'UV index app mention'],
      altHooks: ['„SPF neu auftragen ohne Makeup ruin."', '„Haut schützen im Alltag."'],
      pacing: '15s punchy facts',
      audioTrend: 'Light summer beat',
      visualStyle: 'Office window light',
    },
    {
      title: 'Dupes vs. Luxury — Blind Test',
      platform: 'TikTok',
      hook: '„150€ Serum vs. 12€ Dupe — kannst du den Unterschied sehen?"',
      hookType: 'Comparison',
      hashtags: ['#makeupdupes', '#beautytok', '#skincare', '#budgetbeauty'],
      description: 'Split-screen swatches. Comment-Debatten boosten Reach.',
      views: '1.1M',
      engagement: '8.7%',
      viralScore: 89,
      velocity: 'rising',
      ideas: ['Teil 2: Foundation Dupes', 'Blind test mit Freundin'],
      altHooks: ['„Luxury vs. Drugstore — Ergebnis überrascht."', '„Gleiche Inhaltsstoffe?"'],
      pacing: 'Reveal structure, pause before answer',
      audioTrend: 'Dramatic drum roll trend',
      visualStyle: 'Marble counter, labels blurred',
    },
  ],
  'Side Hustle': [
    {
      title: 'Print on Demand — erste 500€ in 14 Tagen',
      platform: 'TikTok',
      hook: '„Ich hab mit 0 Lagerbestand 500€ gemacht — so startest du."',
      hookType: 'Income Proof',
      hashtags: ['#printondemand', '#sidehustle', '#passiveincome', '#ecommerce'],
      description: 'Screen recordings + earnings blur. Hohe Save-Rate.',
      views: '1.9M',
      engagement: '8.9%',
      viralScore: 88,
      velocity: 'rising',
      ideas: ['Nische-Auswahl Framework', 'Design Tool Tutorial'],
      altHooks: ['„Side Hustle ohne Startkapital."', '„POD für Anfänger erklärt."'],
      pacing: 'Screenshot reveals, bold numbers',
      audioTrend: 'Motivational grind beat',
      visualStyle: 'Dual monitor desk',
    },
    {
      title: 'UGC Portfolio in 48 Stunden',
      platform: 'Instagram',
      hook: '„So landest du deinen ersten UGC-Deal — ohne Follower."',
      hookType: 'Opportunity',
      hashtags: ['#ugc', '#contentcreator', '#sidehustle', '#freelance'],
      description: 'Portfolio walkthrough. B2B-ästhetik auf Instagram.',
      views: '740K',
      engagement: '7.3%',
      viralScore: 83,
      velocity: 'stable',
      ideas: ['Pitch Template Carousel', 'Rate Card Beispiel'],
      altHooks: ['„UGC statt Influencer Marketing."', '„Erster Deal in einer Woche."'],
      pacing: 'Case study slides',
      audioTrend: 'Corporate chill hop',
      visualStyle: 'Notion + Canva screens',
    },
    {
      title: 'Etsy Digital Products — passive Verkäufe',
      platform: 'TikTok',
      hook: '„Ein PDF verkauft sich 200x im Schlaf — hier ist das Template."',
      hookType: 'Passive Income',
      hashtags: ['#etsy', '#digitalproducts', '#sidehustle', '#creatoreconomy'],
      description: 'Etsy dashboard (blurred) + product mockups.',
      views: '1.3M',
      engagement: '9.0%',
      viralScore: 87,
      velocity: 'peak',
      ideas: ['5 profitable Nischen', 'Listing SEO Tipps'],
      altHooks: ['„Digital Products ohne Design-Skills."', '„Etsy Algorithmus 2025."'],
      pacing: 'List format on screen',
      audioTrend: 'Lo-fi hustle',
      visualStyle: 'iPad + coffee shop',
    },
    {
      title: 'Freelance Preise — was du wirklich verlangen solltest',
      platform: 'TikTok',
      hook: '„Du unterverkaufst dich — rechne das so um."',
      hookType: 'Pain + Calculator',
      hashtags: ['#freelance', '#pricing', '#sidehustle', '#solopreneur'],
      description: 'Whiteboard-style numbers. Starke Comments von Freelancern.',
      views: '620K',
      engagement: '8.2%',
      viralScore: 84,
      velocity: 'stable',
      ideas: ['Rate Card Template', 'Client Red Flags'],
      altHooks: ['„Mehr Geld als 9-to-5?"', '„So kalkulierst du Projekte."'],
      pacing: 'Calculator screen + voice',
      audioTrend: 'Serious talk beat',
      visualStyle: 'Notebook, pen, laptop',
    },
    {
      title: 'Affiliate TikTok — ohne cringe Werbung',
      platform: 'TikTok',
      hook: '„Affiliate Links ohne Salesy Vibe — 3 Content-Formate."',
      hookType: 'Method Reveal',
      hashtags: ['#affiliatemarketing', '#tiktokmonetization', '#sidehustle', '#creatorfund'],
      description: 'Examples of native product integration.',
      views: '980K',
      engagement: '7.7%',
      viralScore: 82,
      velocity: 'rising',
      ideas: ['Disclosure richtig machen', 'Nische mit hoher Commission'],
      altHooks: ['„Geld mit TikTok ohne Brand Deals."', '„Authentisch verkaufen."'],
      pacing: 'Example clip montage',
      audioTrend: 'Trending sound under VO',
      visualStyle: 'Casual talking head',
    },
    {
      title: 'Weekend Reseller Flip — 200€ Profit',
      platform: 'Instagram',
      hook: '„Flohmarkt Fund für 8€ — Verkauf für 95€."',
      hookType: 'Flip Story',
      hashtags: ['#reseller', '#thrifting', '#sidehustle', '#vinted'],
      description: 'Before/after item photos. Aesthetic thrift content.',
      views: '510K',
      engagement: '6.8%',
      viralScore: 79,
      velocity: 'stable',
      ideas: ['Was sich lohnt zu flippen', 'Listing Foto Tipps'],
      altHooks: ['„Nebenverdienst am Wochenende."', '„Reselling für Einsteiger."'],
      pacing: 'Photo carousel style in reel',
      audioTrend: 'Vintage chill',
      visualStyle: 'Thrift store finds flat lay',
    },
  ],
  Food: [
    {
      title: 'High Protein Pasta — 5 Zutaten',
      platform: 'TikTok',
      hook: '„Cremige Protein-Pasta in 12 Minuten — Rezept free."',
      hookType: 'Recipe + Time',
      hashtags: ['#highprotein', '#foodtok', '#easyrecipes', '#mealprep'],
      description: 'Top-down cooking. Comment section = recipe requests.',
      views: '2.8M',
      engagement: '10.5%',
      viralScore: 92,
      velocity: 'rising',
      ideas: ['Vegan Variante', 'Makros on screen'],
      altHooks: ['„40g Protein pro Portion."', '„Studentenfreundlich günstig."'],
      pacing: 'ASMR chops, fast ingredient adds',
      audioTrend: 'Cooking ASMR viral',
      visualStyle: 'Bright kitchen, overhead rig',
    },
    {
      title: 'Berlin Hidden Food Spots — 3 Orte',
      platform: 'Instagram',
      hook: '„Tourist Trap? Diese 3 Spots kennen nur Locals."',
      hookType: 'Local Secret',
      hashtags: ['#berlinfood', '#foodreels', '#hidden gems', '#streetfood'],
      description: 'POV walking + food shots. Map pin saves.',
      views: '1.0M',
      engagement: '7.0%',
      viralScore: 83,
      velocity: 'peak',
      ideas: ['Köln/München Edition', 'Budget unter 10€'],
      altHooks: ['„Bestes Street Food 2025."', '„Wo Berliner wirklich essen."'],
      pacing: 'Walk transitions, bite close-up',
      audioTrend: 'Urban exploration beat',
      visualStyle: 'Handheld street, natural color',
    },
    {
      title: 'One Pan Dinner — Busy Weeknight',
      platform: 'TikTok',
      hook: '„Eine Pfanne, 20 Minuten, zero Abwasch-Stress."',
      hookType: 'Convenience',
      hashtags: ['#onepanmeal', '#dinnerideas', '#foodhacks', '#quickmeals'],
      description: 'Satisfying one-pan sizzle. Family audience shares.',
      views: '1.5M',
      engagement: '8.3%',
      viralScore: 86,
      velocity: 'stable',
      ideas: ['Vegetarisch Option', 'Meal prep 4 portions'],
      altHooks: ['„Abendessen ohne Chaos."', '„Faule Küche approved."'],
      pacing: 'Single shot pan cook',
      audioTrend: 'Sizzle ASMR',
      visualStyle: 'Home stove, cozy evening',
    },
    {
      title: 'Aesthetic Lunch Box — Office Edition',
      platform: 'Instagram',
      hook: '„Coworker neidisch — so packst du dein Lunchbox."',
      hookType: 'Social Proof',
      hashtags: ['#lunchbox', '#mealprep', '#office lunch', '#aestheticfood'],
      description: 'Bento-style assembly. High saves from meal preppers.',
      views: '680K',
      engagement: '6.5%',
      viralScore: 80,
      velocity: 'stable',
      ideas: ['5 Tage Plan PDF', 'Vegetarian bento'],
      altHooks: ['„Meal Prep ohne langweilig."', '„Pretty food = mehr Disziplin."'],
      pacing: 'Assembly timelapse',
      audioTrend: 'Soft morning jazz',
      visualStyle: 'Wooden board, natural light',
    },
    {
      title: '3 Ingredient Dessert — Viral Bake',
      platform: 'TikTok',
      hook: '„Dieses 3-Zutaten Dessert bricht gerade TikTok."',
      hookType: 'Viral Trend',
      hashtags: ['#easybaking', '#desserttok', '#foodtrend', '#3ingredients'],
      description: 'Simple bake, gooey reveal shot. Trend-jacking format.',
      views: '3.4M',
      engagement: '11.0%',
      viralScore: 95,
      velocity: 'rising',
      ideas: ['Chocolate vs. Berry', 'Air Fryer version'],
      altHooks: ['„Backen ohne Skill."', '„Süßer Craving Fix in 15 Min."'],
      pacing: 'Mix, bake, reveal money shot',
      audioTrend: 'Oh no trend remix baking',
      visualStyle: 'Kitchen counter, warm tones',
    },
    {
      title: 'Budget Einkauf — 7 Tage unter 35€',
      platform: 'TikTok',
      hook: '„7 Tage Essen für 35€ — Einkaufszettel in Bio."',
      hookType: 'Budget Challenge',
      hashtags: ['#budgetmeals', '#studentmeals', '#foodtok', '#groceryhaul'],
      description: 'Receipt + haul + plate shots. Practical saves.',
      views: '890K',
      engagement: '8.0%',
      viralScore: 84,
      velocity: 'stable',
      ideas: ['Aldi vs. Rewe Vergleich', 'Protein on budget'],
      altHooks: ['„Günstig essen ohne Instant-Nudeln."', '„Inflation Hack."'],
      pacing: 'Receipt zoom + montage',
      audioTrend: 'Upbeat planning beat',
      visualStyle: 'Shopping cart POV',
    },
  ],
  Luxury: [
    {
      title: 'Quiet Luxury Capsule — 6 Looks',
      platform: 'Instagram',
      hook: '„Quiet Luxury ohne Designer-Preis — 6 Looks Breakdown."',
      hookType: 'Aesthetic List',
      hashtags: ['#quietluxury', '#oldmoney', '#capsulewardrobe', '#luxuryreels'],
      description: 'Slow zoom outfit transitions. High save rate.',
      views: '1.1M',
      engagement: '7.2%',
      viralScore: 84,
      velocity: 'peak',
      ideas: ['Brand alternatives list', 'Color palette guide'],
      altHooks: ['„Old Money Aesthetic erklärt."', '„Capsule ohne Shopping-Fail."'],
      pacing: '2s per look, soft transitions',
      audioTrend: 'Ambient jazz luxury',
      visualStyle: 'Neutral linen, soft shadows',
    },
    {
      title: 'Hotel Lobby Aesthetic — iPhone Only',
      platform: 'TikTok',
      hook: '„5-Star Vibes ohne 5-Star Budget — iPhone Tricks."',
      hookType: 'Aspirational Hack',
      hashtags: ['#luxuryaesthetic', '#traveltok', '#iphonephotography', '#hotellife'],
      description: 'Camera settings + angles. Travel niche crossover.',
      views: '1.4M',
      engagement: '8.1%',
      viralScore: 87,
      velocity: 'rising',
      ideas: ['Editing preset free', 'Locations in DACH'],
      altHooks: ['„Luxury Content mit Handy."', '„Lobby Shots die viral gehen."'],
      pacing: 'Before/after edit',
      audioTrend: 'Cinematic travel drone',
      visualStyle: 'Marble, gold accents, moody',
    },
    {
      title: 'Watch / Jewelry Styling — Subtle Flex',
      platform: 'Instagram',
      hook: '„Quiet flex: So stylst du Accessories ohne cringe."',
      hookType: 'Style Guide',
      hashtags: ['#luxurystyle', '#jewelry', '#mensfashion', '#quietflex'],
      description: 'Close-up wrist shots. Male luxury audience growing.',
      views: '520K',
      engagement: '6.2%',
      viralScore: 78,
      velocity: 'stable',
      ideas: ['Women’s version', 'Budget look-alikes'],
      altHooks: ['„Luxury ohne Logo-Overload."', '„Eleganz in Details."'],
      pacing: 'Macro detail shots',
      audioTrend: 'Minimal classical',
      visualStyle: 'Dark suit, shallow DOF',
    },
    {
      title: 'Penthouse Morning Routine — Cinematic',
      platform: 'TikTok',
      hook: '„Morning Routine aber make it old money."',
      hookType: 'Routine + Aesthetic',
      hashtags: ['#morningroutine', '#luxurylifestyle', '#aesthetic', '#penthouse'],
      description: 'Cinematic B-roll montage. Aspiration-driven views.',
      views: '2.0M',
      engagement: '7.9%',
      viralScore: 88,
      velocity: 'rising',
      ideas: ['Evening routine counterpart', 'Sound design focus'],
      altHooks: ['„Luxury Life POV."', '„So startet der 1%-Look."'],
      pacing: 'Slow motion, color graded',
      audioTrend: 'Orchestral morning trend',
      visualStyle: 'Floor-to-ceiling windows, beige tones',
    },
    {
      title: 'Car Interior Detail — Luxury Clean',
      platform: 'TikTok',
      hook: '„Interior Detail macht jedes Auto teurer aus."',
      hookType: 'Transformation',
      hashtags: ['#cardetailing', '#luxurycars', '#cleantok', '#satisfying'],
      description: 'Satisfying cleaning clips. Cross-niche appeal.',
      views: '1.7M',
      engagement: '9.3%',
      viralScore: 90,
      velocity: 'peak',
      ideas: ['Budget products list', 'Before/after split'],
      altHooks: ['„Showroom Finish zu Hause."', '„Luxury Vibes im Auto."'],
      pacing: 'ASMR scrub, reveal',
      audioTrend: 'ASMR cleaning viral',
      visualStyle: 'Leather interior, close macro',
    },
    {
      title: 'Fine Dining Plate — Home Plating',
      platform: 'Instagram',
      hook: '„Michelin Plate zu Hause — 3 Plating Rules."',
      hookType: 'Skill Tutorial',
      hashtags: ['#plating', '#finedining', '#luxuryfood', '#cheftok'],
      description: 'Chef-style plating tutorial. Food × luxury crossover.',
      views: '430K',
      engagement: '6.8%',
      viralScore: 76,
      velocity: 'stable',
      ideas: ['Sauce dot technique', 'Home dinner party menu'],
      altHooks: ['„Restaurant Look zuhause."', '„Gäste beeindrucken in 10 Min."'],
      pacing: 'Top-down plating steps',
      audioTrend: 'Fine dining ambience',
      visualStyle: 'Dark plate, tweezers, garnish',
    },
  ],
  Motivation: [
    {
      title: 'Discipline > Motivation — 60 Sekunden Rant',
      platform: 'TikTok',
      hook: '„Motivation ist eine Lüge — Discipline ist der Cheat Code."',
      hookType: 'Contrarian Rant',
      hashtags: ['#motivation', '#discipline', '#mindset', '#growthtok'],
      description: 'Intense talking head. High share among gym/study audience.',
      views: '4.2M',
      engagement: '11.8%',
      viralScore: 96,
      velocity: 'rising',
      ideas: ['Teil 2: Systems not Goals', 'Stitch reactions'],
      altHooks: ['„So wachst du auch ohne Motivation auf."', '„Hard truth über Erfolg."'],
      pacing: 'Fast cuts on emphasis words',
      audioTrend: 'Epic motivational speech',
      visualStyle: 'Dark background, face lit',
    },
    {
      title: '5AM Club — was niemand sagt',
      platform: 'Instagram',
      hook: '„5AM Club ist nicht für jeden — check diese 3 Signs."',
      hookType: 'Nuanced Take',
      hashtags: ['#5amclub', '#morningmotivation', '#selfgrowth', '#mindsetreels'],
      description: 'Calmer motivational tone for Instagram.',
      views: '920K',
      engagement: '7.5%',
      viralScore: 85,
      velocity: 'stable',
      ideas: ['Alternative schedules', 'Sleep science refs'],
      altHooks: ['„Früh aufstehen ohne Burnout."', '„Finde deine Peak Hours."'],
      pacing: 'Talking head, b-roll inserts',
      audioTrend: 'Inspirational piano',
      visualStyle: 'Sunrise window, silhouette',
    },
    {
      title: 'Vision Board 2025 — digital Setup',
      platform: 'TikTok',
      hook: '„Vision Board in Pinterest — so wird es Realität."',
      hookType: 'How-To',
      hashtags: ['#visionboard', '#manifestation', '#goals2025', '#motivation'],
      description: 'Screen + manifestation niche. Saves spike Jan.',
      views: '1.3M',
      engagement: '8.4%',
      viralScore: 83,
      velocity: 'peak',
      ideas: ['Quarterly review ritual', 'Notion version'],
      altHooks: ['„Goals visualisieren richtig."', '„2025 Plan in 20 Min."'],
      pacing: 'Screen record + voice',
      audioTrend: 'Dreamy manifest audio',
      visualStyle: 'Laptop, candles, cozy',
    },
    {
      title: 'Gym Motivation — Pre-Workout Speech',
      platform: 'TikTok',
      hook: '„Wenn du heute skipst — hör das bis Ende."',
      hookType: 'Direct Address',
      hashtags: ['#gymmotivation', '#nocexcuses', '#fitnessmindset', '#grind'],
      description: 'Black and white gym footage + VO. Classic format still works.',
      views: '3.6M',
      engagement: '10.1%',
      viralScore: 94,
      velocity: 'rising',
      ideas: ['Study version', 'Work version'],
      altHooks: ['„Keine Ausreden heute."', '„Du vs. du von gestern."'],
      pacing: 'Montage on beat drops',
      audioTrend: 'Phonk + speech sample',
      visualStyle: 'High contrast gym B-roll',
    },
    {
      title: 'Journaling Prompts — Anxiety Relief',
      platform: 'Instagram',
      hook: '„3 Journaling Prompts, die meine Anxiety halbiert haben."',
      hookType: 'Personal Result',
      hashtags: ['#journaling', '#mentalhealth', '#selfcare', '#motivationreels'],
      description: 'Soft wellness aesthetic. Comments share own prompts.',
      views: '760K',
      engagement: '7.8%',
      viralScore: 82,
      velocity: 'stable',
      ideas: ['PDF prompt list', 'Morning vs. night prompts'],
      altHooks: ['„Schreiben statt Scrollen."', '„Mindset Reset in 10 Min."'],
      pacing: 'Writing close-ups, calm voice',
      audioTrend: 'Soft ambient healing',
      visualStyle: 'Journal, tea, rainy window',
    },
    {
      title: 'Comeback Story — 90 Tage später',
      platform: 'TikTok',
      hook: '„Vor 90 Tagen hatte ich null Plan — heute…"',
      hookType: 'Comeback Arc',
      hashtags: ['#comeback', '#glowup', '#motivation', '#storytime'],
      description: 'Photo progression + emotional VO. High completion rate.',
      views: '2.1M',
      engagement: '9.6%',
      viralScore: 91,
      velocity: 'rising',
      ideas: ['Career comeback variant', 'Fitness comeback variant'],
      altHooks: ['„Rock bottom war der Start."', '„So hab ich mich rebuilt."'],
      pacing: 'Photo timeline, music swell',
      audioTrend: 'Emotional build-up track',
      visualStyle: 'Mixed candid photos',
    },
  ],
  AI: [
    {
      title: 'ChatGPT Prompt für Viral Hooks',
      platform: 'TikTok',
      hook: '„Dieser Prompt spuckt 50 Hooks in 2 Minuten aus."',
      hookType: 'Tool Reveal',
      hashtags: ['#chatgpt', '#ai', '#contentcreation', '#hooks'],
      description: 'Screen record prompt + outputs. Meta-content performs well.',
      views: '2.5M',
      engagement: '10.4%',
      viralScore: 93,
      velocity: 'rising',
      ideas: ['Prompt in Caption', 'Instagram Reels version'],
      altHooks: ['„AI für Content Creator."', '„Nie wieder leere Captions."'],
      pacing: 'Screen typing speed-up',
      audioTrend: 'Tech whoosh sounds',
      visualStyle: 'Dark mode ChatGPT UI',
    },
    {
      title: 'AI Thumbnail A/B Test — CTR +40%',
      platform: 'Instagram',
      hook: '„Zwei Thumbnails, ein Winner — AI hat entschieden."',
      hookType: 'Result Proof',
      hashtags: ['#aicontent', '#youtube tips', '#thumbnail', '#creatortools'],
      description: 'Analytics screenshot + AI tool. Creator niche.',
      views: '680K',
      engagement: '7.1%',
      viralScore: 84,
      velocity: 'stable',
      ideas: ['Tool stack carousel', 'Title generator prompts'],
      altHooks: ['„CTR mit AI optimieren."', '„Thumbnail in 30 Sekunden."'],
      pacing: 'Split screen compare',
      audioTrend: 'Digital glitch beat',
      visualStyle: 'Analytics dashboard blur',
    },
    {
      title: 'Automate Instagram Captions — Workflow',
      platform: 'TikTok',
      hook: '„Mein Content Kalender läuft halb auf Autopilot — Setup."',
      hookType: 'Workflow',
      hashtags: ['#aiworkflow', '#instagramgrowth', '#automation', '#socialmediatips'],
      description: 'Notion + AI tool chain demo.',
      views: '1.1M',
      engagement: '8.2%',
      viralScore: 86,
      velocity: 'stable',
      ideas: ['Zapier alternative', 'Batch content Sunday'],
      altHooks: ['„Weniger Zeit am Handy."', '„AI Batch Writing erklärt."'],
      pacing: 'Workflow diagram animation',
      audioTrend: 'Productivity tech beat',
      visualStyle: 'Multi-app screens',
    },
    {
      title: 'AI Avatar Videos — Faceless Channel',
      platform: 'TikTok',
      hook: '„Faceless Channel mit AI Avatars — Schritt für Schritt."',
      hookType: 'Tutorial',
      hashtags: ['#faceless', '#aivideo', '#youtubeautomation', '#aitools'],
      description: 'Controversial but high search volume topic.',
      views: '1.8M',
      engagement: '7.9%',
      viralScore: 85,
      velocity: 'rising',
      ideas: ['Ethics disclaimer', 'Niche selection guide'],
      altHooks: ['„Ohne Gesicht auf TikTok wachsen."', '„AI Video Pipeline 2025."'],
      pacing: 'Tool demo montage',
      audioTrend: 'Futuristic synth',
      visualStyle: 'AI avatar preview screens',
    },
    {
      title: 'Midjourney Aesthetic für Reels Covers',
      platform: 'Instagram',
      hook: '„Reels Cover in Midjourney — Brand Look in 5 Prompts."',
      hookType: 'Design Hack',
      hashtags: ['#midjourney', '#aidesign', '#reelscover', '#branding'],
      description: 'Visual designers + marketers save this.',
      views: '540K',
      engagement: '6.9%',
      viralScore: 80,
      velocity: 'stable',
      ideas: ['Prompt pack PDF', 'Color match tip'],
      altHooks: ['„Ästhetische Covers ohne Designer."', '„AI Branding Hack."'],
      pacing: 'Prompt → result reveals',
      audioTrend: 'Creative flow music',
      visualStyle: 'Grid of AI images',
    },
    {
      title: 'AI Trend Research — vor der Konkurrenz',
      platform: 'TikTok',
      hook: '„So findest du Trends bevor sie saturated sind — mit AI."',
      hookType: 'Strategy',
      hashtags: ['#trendresearch', '#ai', '#socialmediastrategy', '#earlytrends'],
      description: 'Ties into NexTrends value prop naturally.',
      views: '970K',
      engagement: '8.8%',
      viralScore: 89,
      velocity: 'rising',
      ideas: ['NexTrends workflow tease', 'Hashtag velocity metric'],
      altHooks: ['„Trend Scouting automatisiert."', '„Nische finden mit AI."'],
      pacing: 'Dashboard style mock + tips',
      audioTrend: 'Data tech pulse',
      visualStyle: 'Purple UI mock, charts',
    },
  ],
  Business: [
    {
      title: 'Pitch Deck Slide — Investor Ready',
      platform: 'Instagram',
      hook: '„Slide 3 hat uns die Funding Runde gerettet — Breakdown."',
      hookType: 'Insider Reveal',
      hashtags: ['#pitchdeck', '#startup', '#founder', '#venturecapital'],
      description: 'Professional founder content for Instagram.',
      views: '620K',
      engagement: '6.4%',
      viralScore: 81,
      velocity: 'stable',
      ideas: ['Full deck structure carousel', 'Design tool recs'],
      altHooks: ['„Investor Pitch der überzeugt."', '„Startup Deck Template."'],
      pacing: 'Slide walkthrough',
      audioTrend: 'Corporate inspiring',
      visualStyle: 'Clean slides, laptop',
    },
    {
      title: 'LinkedIn Personal Brand — 30 Tage Plan',
      platform: 'Instagram',
      hook: '„LinkedIn Personal Brand in 30 Tagen — Tag 1 Start."',
      hookType: 'Challenge',
      hashtags: ['#linkedin', '#personalbrand', '#b2b', '#foundertips'],
      description: 'B2B creators repurpose to Reels.',
      views: '480K',
      engagement: '5.9%',
      viralScore: 77,
      velocity: 'stable',
      ideas: ['Post templates', 'Headline formulas'],
      altHooks: ['„B2B Leads über LinkedIn."', '„Personal Brand ohne cringe."'],
      pacing: 'Talking head + text cards',
      audioTrend: 'Neutral corporate',
      visualStyle: 'Office, blazer, neutral bg',
    },
    {
      title: 'SaaS Pricing Page — Conversion Fix',
      platform: 'TikTok',
      hook: '„Eine Pricing-Änderung = +23% Conversion — Case Study."',
      hookType: 'Case Study',
      hashtags: ['#saas', '#conversion', '#pricing', '#growthmarketing'],
      description: 'Screenshot before/after. Indie hacker audience.',
      views: '710K',
      engagement: '7.6%',
      viralScore: 83,
      velocity: 'rising',
      ideas: ['A/B test framework', 'Copy swipe file'],
      altHooks: ['„Pricing Psychology erklärt."', '„SaaS Wachstum Hack."'],
      pacing: 'Heatmap + pricing table',
      audioTrend: 'Startup podcast clip',
      visualStyle: 'SaaS UI mock',
    },
    {
      title: 'Cold DM Script — 12% Reply Rate',
      platform: 'TikTok',
      hook: '„Cold DMs die nicht cringe sind — Copy Paste Script."',
      hookType: 'Script Share',
      hashtags: ['#coldoutreach', '#sales', '#founder', '#growthhacks'],
      description: 'On-screen script + results blur.',
      views: '890K',
      engagement: '8.0%',
      viralScore: 84,
      velocity: 'stable',
      ideas: ['Follow-up sequence', 'LinkedIn variant'],
      altHooks: ['„Mehr Replies auf DMs."', '„Sales ohne awkward Pitch."'],
      pacing: 'Script scroll, highlight lines',
      audioTrend: 'Hustle beat low key',
      visualStyle: 'Phone screen, notifications',
    },
    {
      title: 'Meeting Notes → Action Items mit AI',
      platform: 'TikTok',
      hook: '„1h Meeting in 3 Bullet Actions — AI Workflow."',
      hookType: 'Productivity',
      hashtags: ['#meetings', '#ai', '#productivity', '#founderlife'],
      description: 'Office productivity crossover.',
      views: '1.0M',
      engagement: '7.8%',
      viralScore: 82,
      velocity: 'rising',
      ideas: ['Tool comparison', 'Notion template'],
      altHooks: ['„Meetings die nicht Zeit killen."', '„AI Notes für Teams."'],
      pacing: 'Screen capture workflow',
      audioTrend: 'Office lo-fi',
      visualStyle: 'Zoom blur, notion page',
    },
    {
      title: 'Newsletter Launch — 0 to 1000 Subs',
      platform: 'Instagram',
      hook: '„Newsletter von 0 auf 1000 in 6 Wochen — Playbook."',
      hookType: 'Growth Playbook',
      hashtags: ['#newsletter', '#emailmarketing', '#creatorbusiness', '#subs'],
      description: 'Creator economy business content.',
      views: '550K',
      engagement: '6.7%',
      viralScore: 79,
      velocity: 'stable',
      ideas: ['Lead magnet ideas', 'Welcome sequence'],
      altHooks: ['„Email List aufbauen 2025."', '„Newsletter als Business."'],
      pacing: 'Stats graph animation',
      audioTrend: 'Soft growth theme',
      visualStyle: 'Beehiiv/Substack mock',
    },
  ],
  Fashion: [
    {
      title: 'Spring Capsule — 10 Pieces, 20 Outfits',
      platform: 'Instagram',
      hook: '„10 Teile, 20 Outfits — Spring Capsule Reveal."',
      hookType: 'Capsule',
      hashtags: ['#capsulewardrobe', '#springfashion', '#ootd', '#fashionreels'],
      description: 'Outfit transitions classic fashion format.',
      views: '1.3M',
      engagement: '7.4%',
      viralScore: 85,
      velocity: 'peak',
      ideas: ['Shopping list', 'Thrift version'],
      altHooks: ['„Weniger Kleidung, mehr Outfits."', '„Frühling 2025 Trends."'],
      pacing: 'Rapid outfit changes',
      audioTrend: 'Fashion week remix',
      visualStyle: 'Minimal backdrop, full body',
    },
    {
      title: 'Thrift Flip — Vintage Denim',
      platform: 'TikTok',
      hook: '„Thrift Denim für 6€ — nachher sieht es Designer aus."',
      hookType: 'Transformation',
      hashtags: ['#thriftflip', '#upcycling', '#denim', '#sustainablefashion'],
      description: 'Sewing/quick fix transformation.',
      views: '1.6M',
      engagement: '8.9%',
      viralScore: 88,
      velocity: 'rising',
      ideas: ['Before/after side by side', 'Toolkit under 20€'],
      altHooks: ['„Vintage ohne Vintage-Preis."', '„DIY Fashion Hack."'],
      pacing: 'Transformation reveal',
      audioTrend: 'Upbeat DIY trend',
      visualStyle: 'Thrift store, sewing machine',
    },
    {
      title: 'Color Analysis — Welche Farben dir stehen',
      platform: 'TikTok',
      hook: '„Warm Autumn? Cool Winter? 60-Sekunden Color Test."',
      hookType: 'Quiz',
      hashtags: ['#coloranalysis', '#fashiontok', '#styletips', '#personalcolor'],
      description: 'Interactive style content drives comments.',
      views: '2.3M',
      engagement: '9.7%',
      viralScore: 91,
      velocity: 'rising',
      ideas: ['Drape test demo', 'Palette carousel'],
      altHooks: ['„Farben die dich älter machen."', '„Outfit Farben die wirken."'],
      pacing: 'Fabric swatch comparisons',
      audioTrend: 'Trend pop bright',
      visualStyle: 'Natural light, face focus',
    },
    {
      title: 'Street Style Berlin — Trend Scan',
      platform: 'Instagram',
      hook: '„Was Berlin gerade trägt — 5 Micro-Trends."',
      hookType: 'Street Report',
      hashtags: ['#streetstyle', '#berlinfashion', '#trendreport', '#styleinspo'],
      description: 'Street interview style b-roll.',
      views: '780K',
      engagement: '6.8%',
      viralScore: 80,
      velocity: 'stable',
      ideas: ['München/Hamburg edition', 'Men’s street style'],
      altHooks: ['„Fashion Trends live von der Straße."', '„Berlin Style Check."'],
      pacing: 'Quick cuts street clips',
      audioTrend: 'Urban fashion beat',
      visualStyle: 'Handheld street, diverse looks',
    },
    {
      title: 'Zara Haul — Styling 5 Pieces',
      platform: 'TikTok',
      hook: '„Zara Haul aber jedes Piece 3x anders gestylt."',
      hookType: 'Haul + Styling',
      hashtags: ['#zarhaul', '#haul', '#fashiontok', '#stylingtips'],
      description: 'Haul format evergreen on TikTok.',
      views: '2.9M',
      engagement: '10.2%',
      viralScore: 92,
      velocity: 'peak',
      ideas: ['Return policy tips', 'Size guide hack'],
      altHooks: ['„Zara Finds die viral gehen."', '„Budget High Street Style."'],
      pacing: 'Try-on montage',
      audioTrend: 'Haul trending sound',
      visualStyle: 'Bedroom mirror, ring light',
    },
    {
      title: 'Accessories Layering — Elevate Basic Fit',
      platform: 'Instagram',
      hook: '„Basic Hoodie → Premium Look — nur Accessories."',
      hookType: 'Styling Hack',
      hashtags: ['#accessories', '#stylehack', '#fashiontips', '#elevatedbasics'],
      description: 'Quick styling hack, high saves.',
      views: '640K',
      engagement: '7.0%',
      viralScore: 81,
      velocity: 'stable',
      ideas: ['Men’s accessory version', 'Budget vs. luxury accessories'],
      altHooks: ['„Outfit Upgrade ohne neues Outfit."', '„Layering Tricks."'],
      pacing: 'Before/after same base outfit',
      audioTrend: 'Chic minimal beat',
      visualStyle: 'Mirror selfie, neutral wall',
    },
  ],
}

function slugify(niche: string): string {
  return niche.toLowerCase().replace(/\s+/g, '-')
}

function estimateLikes(views: string, engagement: string): string {
  const v = parseFloat(views.replace(/[MK]/g, '')) * (views.includes('M') ? 1_000_000 : 1_000)
  const e = parseFloat(engagement.replace('%', '').replace(',', '.')) || 8
  const likes = Math.round(v * (e / 100) * 0.35)
  if (likes >= 1_000_000) return `${(likes / 1_000_000).toFixed(1).replace('.0', '')}M`
  if (likes >= 1_000) return `${Math.round(likes / 1_000)}K`
  return String(likes)
}

function buildTrendFromBlueprint(
  niche: DemoCatalogNiche,
  blueprint: TrendBlueprint,
  globalIndex: number,
  nicheIndex: number,
  usedVideos: Set<string>,
  usedThumbnails: Set<string>,
  usedCreators: Set<string>,
  usedHooks: Set<string>,
): TrendIntelligence {
  const id = `demo-${slugify(niche)}-${nicheIndex}`
  const gradient = GRADIENTS[globalIndex % GRADIENTS.length]
  const media = resolveUniqueCatalogMedia(globalIndex, usedVideos, usedThumbnails)
  const creator = assignCreatorForCatalogSlot(globalIndex, id, blueprint.platform, usedCreators)
  const hookScore = clampScore(blueprint.viralScore - 3 + (globalIndex % 5))
  const hookText = blueprint.hook
  usedHooks.add(hookText)

  return {
    id,
    title: blueprint.title,
    platform: blueprint.platform,
    views: blueprint.views,
    likes: estimateLikes(blueprint.views, blueprint.engagement),
    engagement: blueprint.engagement,
    engagementRate: blueprint.engagement,
    description: blueprint.description,
    gradientFrom: gradient.from,
    gradientTo: gradient.to,
    viralScore: blueprint.viralScore,
    trendVelocity: blueprint.velocity,
    hashtags: blueprint.hashtags,
    engagementPrediction: `${blueprint.engagement.replace('%', '')}–${(parseFloat(blueprint.engagement) + 1.2).toFixed(1)} % erwartet in den nächsten 72h.`,
    contentIdeas: blueprint.ideas,
    hookSuggestions: blueprint.altHooks,
    creatorInspiration: formatCreatorInspiration(creator, blueprint.platform),
    thumbnailUrl: media.poster,
    videoUrl: media.video,
    videoDuration: media.duration,
    creator,
    hookAnalysis: {
      hookType: blueprint.hookType,
      hookText,
      hookScore,
      whyItWorks:
        'Starker Scroll-Stop in Sekunde 1. Das Format passt zur Plattform-Gewohnheit der Zielgruppe.',
      retentionTrigger: 'Pattern Interrupt bei Sekunde 2–4 — hält Watch-Time stabil',
    },
    contentBreakdown: {
      format:
        blueprint.platform === 'Instagram' ? 'Reel · 9:16 · 15–45s' : 'Short-Form · 9:16 · 30–60s',
      pacing: blueprint.pacing,
      audioTrend: blueprint.audioTrend,
      visualStyle: blueprint.visualStyle,
      ctaStrategy: 'Soft CTA: Speichern & Folgen — hohe Save-Rate in der Nische',
      bestPostTime: 'Di–Do · 18:00–21:00 Uhr (DACH Peak)',
    },
    externalUrl:
      blueprint.platform === 'Instagram' ? 'https://www.instagram.com' : 'https://www.tiktok.com',
    niche,
    isDemo: true,
  }
}

function clampScore(score: number): number {
  return Math.min(99, Math.max(42, Math.round(score)))
}

const CATALOG_MEDIA_VERSION = 2

let catalogCache: TrendIntelligence[] | null = null
let catalogMediaVersion: number | null = null

export function getDemoTrendCatalog(): TrendIntelligence[] {
  if (catalogCache && catalogMediaVersion === CATALOG_MEDIA_VERSION) return catalogCache

  const trends: TrendIntelligence[] = []
  const usedVideos = new Set<string>()
  const usedThumbnails = new Set<string>()
  const usedCreators = new Set<string>()
  const usedHooks = new Set<string>()
  let index = 0

  for (const niche of DEMO_CATALOG_NICHES) {
    let nicheIndex = 0
    for (const blueprint of NICHE_BLUEPRINTS[niche]) {
      trends.push(
        buildTrendFromBlueprint(
          niche,
          blueprint,
          index,
          nicheIndex,
          usedVideos,
          usedThumbnails,
          usedCreators,
          usedHooks,
        ),
      )
      index += 1
      nicheIndex += 1
    }
  }

  catalogCache = trends
  catalogMediaVersion = CATALOG_MEDIA_VERSION
  assertUniqueTrendCatalog(catalogCache)
  return catalogCache
}

/** Curated hero set for first-time demo browse */
export function getDemoShowcaseTrends(count = 4): TrendIntelligence[] {
  const picks = [
    'demo-productivity-0',
    'demo-fashion-0',
    'demo-beauty-0',
    'demo-ai-0',
    'demo-fitness-0',
    'demo-luxury-0',
  ]
  const catalog = getDemoTrendCatalog()
  const byId = new Map(catalog.map((t) => [t.id, t]))
  return picks
    .map((id) => byId.get(id))
    .filter((t): t is TrendIntelligence => Boolean(t))
    .slice(0, count)
}
