import type { VideoBlueprint } from '@/types/video-blueprint'

export function blueprintToMarkdown(blueprint: VideoBlueprint): string {
  const lines: string[] = [
    `# NexTrends AI Video Blueprint`,
    ``,
    `**${blueprint.trendTitle}** · ${blueprint.platform} · ${blueprint.niche}`,
    ``,
    `## Video Concept`,
    blueprint.concept,
    ``,
    `## Hooks (0–3s)`,
    ...blueprint.hooks.map(
      (h, i) => `${i + 1}. **${h.text}** (${h.style}, Retention ${h.retentionScore}/100)`,
    ),
    ``,
    `## Scene Breakdown`,
    ...blueprint.scenes.map(
      (s) =>
        `### Scene ${s.id}: ${s.label} (${s.timeRange})\n` +
        `- Camera: ${s.cameraAngle}\n` +
        `- Visual: ${s.visualDirection}\n` +
        `- Pacing: ${s.pacing}\n` +
        `- Overlay: ${s.overlayText}`,
    ),
    ``,
    `## Voiceover Script`,
    blueprint.pipeline.voiceover.script,
    ``,
    `## Shot List`,
    ...blueprint.pipeline.shots.items.map(
      (s) => `### Scene ${s.sceneId}\n${s.prompt}`,
    ),
    ``,
    `## Captions`,
    ...blueprint.captions.map((c) => `- ${c}`),
    ``,
    `## CTA Ending`,
    `- Engagement: ${blueprint.cta.engagement}`,
    `- Follow: ${blueprint.cta.follow}`,
    `- Comment bait: ${blueprint.cta.commentBait}`,
    ``,
    `## Viral Elements`,
    blueprint.viralElements.performanceHypothesis,
    ``,
    `**Emotional triggers:** ${blueprint.viralElements.emotionalTriggers.join(', ')}`,
    ``,
    `**Algorithm fit:**`,
    ...blueprint.viralElements.algorithmFit.map((a) => `- ${a}`),
    ``,
    `## Platform Optimization`,
    `- TikTok: ${blueprint.platformOptimization.tiktok}`,
    `- Reels: ${blueprint.platformOptimization.reels}`,
    `- Shorts: ${blueprint.platformOptimization.shorts}`,
    ``,
    ...(blueprint.postingStrategy
      ? [`## Posting Strategy`, blueprint.postingStrategy, ``]
      : []),
    `---`,
    `Generated by NexTrends Creator OS · ${blueprint.createdAt}`,
  ]
  return lines.join('\n')
}

export function downloadBlueprint(blueprint: VideoBlueprint, format: 'json' | 'markdown'): void {
  const isJson = format === 'json'
  const content = isJson ? JSON.stringify(blueprint, null, 2) : blueprintToMarkdown(blueprint)
  const blob = new Blob([content], {
    type: isJson ? 'application/json' : 'text/markdown;charset=utf-8',
  })
  const slug = blueprint.trendTitle.slice(0, 40).replace(/[^\w-]+/g, '-').toLowerCase()
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `nextrends-blueprint-${slug}.${isJson ? 'json' : 'md'}`
  anchor.click()
  URL.revokeObjectURL(url)
}

export function blueprintToClipboardText(blueprint: VideoBlueprint): string {
  return blueprintToMarkdown(blueprint)
}
